### ISSUE TITLE
File Downloading doesn't work!

### ISSUE THREAD

**Issue by 100pcrack** [thejsa/KoopaCruiser#3]
When I press X to download files it says "saving index.html" and nothing happens.
This error appears on precomplied build and on a home-complied build.
O3DS 10.3 Ninjhax *hax 2.5
Screenshots:
![TOPSCREEN](http://i.imgur.com/Ek2jZBW.png)
![BOTTOMSCREEN](http://i.imgur.com/FH5fItN.png)
Hope I can help!

**Comment by thejsa** [comment]
Hi @100pcrack actually it has worked - look and you'll see it says "saved to index.html" :)

**Comment by 100pcrack** [comment]
Yes, but it dowsn't diplay image.
Should it?

**Comment by thejsa** [comment]
@100pcrack no, it saves it to wherever you put the 3DSX.

Also looks like I uploaded the build which downloads whatever the URL is set to in the source code so I should update that

**Comment by 100pcrack** [comment]
Ok.
Hope I have been helpfull.
Maybe you could use Devkitpro examples to introduce a downloaded-image-viewer.

**Comment by thejsa** [comment]
@100pcrack Perhaps.
It would be more useful for viewing images in webpages though :)

**Comment by thejsa** [comment]
@100pcrack Perhaps.
It would be more useful for viewing images in webpages though :)
